### ISSUE TITLE
Simple example with Random Forest / Module Import Error

### ISSUE THREAD

**Issue by val-co** [laudv/ocscore#1]
Hello, thank you for sharing the code. I tried running the run_experiments.sh script, but I get the following error - ModuleNotFoundError: No module named 'data_and_trees'.

So, I was wondering if you could provide me with a simple script wherein I could use a sklearn random forest trained on the IRIS dataset to generate OC-scores from the test dataset? 

Thank you!

**Comment by laudv** [comment]
Hi,

Yes, I'm still working on making that package publicly available, sorry about that.

In the meantime, here is a script that should work without the package. If you comment out the parts in ocscore.pyx that use [veritas](https://github.com/laudv/veritas/tree/finiteprec) and recompile, you can also run it without veritas.

https://github.com/laudv/ocscore/blob/main/mnist_example.py

I hope this is useful!

Laurens

**Comment by val-co** [comment]
Thanks for the quick response! Just one question - In one of the comments, you mention that the mapsids function was used to ensure identifiers are in 0 to 255 for each leaf in the ensemble. Will this be an issue for ensembles with more leaves?

**Comment by laudv** [comment]
Yes, the maximum number of trees and the maximum number of leaves per tree is currently limited to 255. This is due to the use of uint8 here: https://github.com/laudv/ocscore/blob/0e6711483f2b0b6946709468a5964aa45e748c74/ocscore.pyx#L68

One could alleviate this by using uint16, which has 65k possible values, downside being a performance penalty. If you are interested in such an option, let me know.

**Comment by val-co** [comment]
Yes, Thank you! I have slightly larger tree ensembles so that would be helpful for my application!

**Comment by laudv** [comment]
I wrote a quick non-optimized uint16 version of `ocscore.ocscores`, see commit https://github.com/laudv/ocscore/commit/d729dbd7b5e3981a2ab873dee1c060e6369fef3a

If you run into performance issues, or also need the topk version, have a look at what I did or let me know. I'm happy to take a pull request.

I also pulled the veritas dependency out of `ocscore.pyx`. Those functions are now in `ocscore_veritas.py`.

Laurens

**Comment by val-co** [comment]
Thank you for the changes! I have one final question - what is the best way to select the threshold on the OC-scores for determining adversarial examples?

**Comment by laudv** [comment]
That is a difficult problem and very application dependent, and a very common problem in machine learning. One good place to start is to visualize the score distributions of the normal examples and, if you have any, the (adversarial) examples that you want to filter out (see e.g. slide 6 [here](https://people.cs.kuleuven.be/~laurens.devos/files/ocscore-slides.pdf)). You can then see how willing you are given your application to take more false negatives or more false positives.

**Comment by val-co** [comment]
Thank you!
