### ISSUE TITLE
Proof Supplement

### ISSUE THREAD

**Issue by ghost** [laudv/ocscore#2]
Hello, thank you for sharing the code. In the paper, it says that the OC-Score proof is in the supplement. However, I cannot seem to find it. Is it possible to share the proof supplement PDF here? 

Best,
Masooud.

**Comment by laudv** [comment]
Hi Masooud,

You can find the appendix here: https://people.cs.kuleuven.be/~laurens.devos/files/ocscore-appendix.pdf

Laurens
